### PR TITLE
Adding all properties for srr ui

### PR DESCRIPTION
**Pull request by MimiXav**
Signed-off-by: Xavier Millieret <XavierMillieret@eaton.com>

### CODE REVIEW

**Comment by aquette** [comment]
closing/reopening to force full CI, now that builders are refreshed

**Comment by aquette** [comment]
@MimiXav 
There is a remaining pedantic error:
src/fty_srr_worker.h:35:48: error: extra ';' [-Werror=pedantic]

                 std::string featureDescription;;

Please fix and then we'll merge, since jenkins is brain damaged at continuing to build on 2.1.0 worker (cf @perrettecl comment on a wrong modification of the worker name on master).
thx

**Comment by aquette** [comment]
closing in favor of #18, which also fixes the pedantic error
